const http = require('http'), fs = require('fs'), path = require('path'), crypto = require('crypto');
const { DatabaseSync } = require('node:sqlite');
const ROOT = __dirname, PUBLIC = path.join(ROOT, 'public'), UPLOADS = path.join(ROOT, 'uploads');
const db = new DatabaseSync(path.join(ROOT, 'data', 'moviezone.db'));
db.exec(`CREATE TABLE IF NOT EXISTS movies (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT NOT NULL, year INTEGER NOT NULL, language TEXT NOT NULL, category TEXT NOT NULL, poster TEXT, download_url TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const adminUser = process.env.ADMIN_USERNAME || 'admin', adminPass = process.env.ADMIN_PASSWORD || 'moviezone-admin';
const sessions = new Map();
const samples = [
 ['The Last Horizon','A resourceful cartographer races across a shifting desert world to find the city her mother mapped decades ago.',2026,'English','Hollywood','/posters/horizon.svg','https://archive.org/'],
 ['Monsoon Letters','Two strangers exchange anonymous letters during one unforgettable Mumbai monsoon.',2025,'Hindi','Bollywood','/posters/monsoon.svg','https://archive.org/'],
 ['Iron Temple','An archaeologist returns to her coastal hometown when an ancient lighthouse begins to signal again.',2024,'Tamil','South Indian','/posters/temple.svg','https://archive.org/'],
 ['Echoes of Tomorrow','A small team discovers that their forgotten voice notes can alter one day in the future.',2026,'English','Web Series','/posters/echoes.svg','https://archive.org/'],
 ['Paper Kingdom','A charming illustrator learns that the worlds in his sketchbook are quietly becoming real.',2023,'Malayalam','South Indian','/posters/paper.svg','https://archive.org/'],
 ['Midnight Atlas','A late-night radio host follows a constellation of callers toward an unexpected reunion.',2025,'Hindi','Bollywood','/posters/atlas.svg','https://archive.org/']
];
if (!db.prepare('SELECT COUNT(*) n FROM movies').get().n) { const add=db.prepare('INSERT INTO movies(title,description,year,language,category,poster,download_url) VALUES(?,?,?,?,?,?,?)'); for(const m of samples)add.run(...m); }
function send(res, code, data, type='application/json'){res.writeHead(code, {'Content-Type':type, 'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(data):data)}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=').map(decodeURIComponent)))}
function auth(req){return sessions.has(cookies(req).mz_session)}
function multipart(req){return new Promise(resolve=>{let a=[];req.on('data',d=>a.push(d));req.on('end',()=>{let raw=Buffer.concat(a), b=(req.headers['content-type']||'').match(/boundary=(.+)$/);if(!b)return resolve(null);let parts=raw.toString('binary').split('--'+b[1]);for(let x of parts){let h=x.indexOf('\r\n\r\n');if(h<0)continue;let head=x.slice(0,h), name=(head.match(/name=\"([^\"]+)/)||[])[1], fn=(head.match(/filename=\"([^\"]*)/)||[])[1];if(name==='poster'&&fn){let data=Buffer.from(x.slice(h+4).replace(/\r\n$/, ''),'binary'), ext=path.extname(fn).toLowerCase();if(!['.png','.jpg','.jpeg','.webp','.gif'].includes(ext)||data.length>5*1024*1024)return resolve({error:'Upload a PNG, JPG, WEBP, or GIF below 5 MB.'});let file=crypto.randomUUID()+ext;fs.writeFileSync(path.join(UPLOADS,file),data);return resolve({url:'/uploads/'+file})}}resolve({error:'Choose an image to upload.'})})})}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>s+=d);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('Invalid JSON'))}})})}
function movie(row){return {...row, poster:row.poster||'/posters/default.svg'} }
function api(req,res,u){
 const method=req.method, p=u.pathname;
 if(method==='GET'&&p==='/api/movies'){let q=u.searchParams.get('q')||'',category=u.searchParams.get('category')||'',language=u.searchParams.get('language')||'',year=u.searchParams.get('year')||'';let where=[],a=[];if(q){where.push('(title LIKE ? OR description LIKE ?)');a.push('%'+q+'%','%'+q+'%')}if(category){where.push('category=?');a.push(category)}if(language){where.push('language=?');a.push(language)}if(year){where.push('year=?');a.push(year)}let sql='SELECT * FROM movies '+(where.length?'WHERE '+where.join(' AND '):'')+' ORDER BY datetime(created_at) DESC,id DESC';return send(res,200,db.prepare(sql).all(...a).map(movie))}
 if(method==='GET'&&/^\/api\/movies\/\d+$/.test(p)){let m=db.prepare('SELECT * FROM movies WHERE id=?').get(+p.split('/').pop());return m?send(res,200,movie(m)):send(res,404,{error:'Movie not found'})}
 if(method==='GET'&&p==='/api/meta'){return send(res,200,{categories:['Bollywood','Hollywood','South Indian','Web Series'],languages:db.prepare('SELECT DISTINCT language FROM movies ORDER BY language').all().map(x=>x.language),years:db.prepare('SELECT DISTINCT year FROM movies ORDER BY year DESC').all().map(x=>x.year)})}
 if(method==='POST'&&p==='/api/admin/upload'){if(!auth(req))return send(res,401,{error:'Please sign in as an administrator.'});return multipart(req).then(x=>x.error?send(res,400,x):send(res,201,x))}
 if(method==='POST'&&p==='/api/login')return body(req).then(x=>{if(x.username===adminUser&&x.password===adminPass){let t=crypto.randomBytes(32).toString('hex');sessions.set(t,Date.now());res.writeHead(200,{'Set-Cookie':`mz_session=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`,'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true}))}send(res,401,{error:'Incorrect username or password'})}).catch(()=>send(res,400,{error:'Invalid request'}));
 if(method==='POST'&&p==='/api/logout'){let t=cookies(req).mz_session;sessions.delete(t);res.writeHead(200,{'Set-Cookie':'mz_session=; HttpOnly; Path=/; Max-Age=0','Content-Type':'application/json'});return res.end('{"ok":true}')}
 if(method==='GET'&&p==='/api/admin/status')return send(res,200,{authenticated:auth(req)});
 if(!auth(req)&&p.startsWith('/api/admin'))return send(res,401,{error:'Please sign in as an administrator.'});
 if(method==='GET'&&p==='/api/admin/dashboard'){let total=db.prepare('SELECT COUNT(*) n FROM movies').get().n,recent=db.prepare('SELECT * FROM movies ORDER BY datetime(created_at) DESC,id DESC LIMIT 5').all().map(movie);return send(res,200,{total,recent})}
 if(method==='POST'&&p==='/api/admin/movies')return body(req).then(x=>{let r=db.prepare('INSERT INTO movies(title,description,year,language,category,poster,download_url) VALUES(?,?,?,?,?,?,?)').run(x.title,x.description,+x.year,x.language,x.category,x.poster||'/posters/default.svg',x.download_url||'');send(res,201,{id:r.lastInsertRowid})}).catch(()=>send(res,400,{error:'Complete all required fields.'}));
 if(method==='PUT'&&/^\/api\/admin\/movies\/\d+$/.test(p))return body(req).then(x=>{db.prepare('UPDATE movies SET title=?,description=?,year=?,language=?,category=?,poster=?,download_url=? WHERE id=?').run(x.title,x.description,+x.year,x.language,x.category,x.poster||'/posters/default.svg',x.download_url||'',+p.split('/').pop());send(res,200,{ok:true})}).catch(()=>send(res,400,{error:'Unable to update movie.'}));
 if(method==='DELETE'&&/^\/api\/admin\/movies\/\d+$/.test(p)){db.prepare('DELETE FROM movies WHERE id=?').run(+p.split('/').pop());return send(res,200,{ok:true})}
 send(res,404,{error:'Not found'});
}
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon'};
http.createServer((req,res)=>{const u=new URL(req.url,'http://x');if(u.pathname.startsWith('/api/'))return api(req,res,u);let file=u.pathname==='/'?'/index.html':u.pathname;file=path.normalize(file).replace(/^\/+/, '');let root=file.startsWith('uploads/')?ROOT:PUBLIC, target=path.join(root,file);if(!target.startsWith(root)||!fs.existsSync(target)||fs.statSync(target).isDirectory())return send(res,404,'Not found','text/plain');send(res,200,fs.readFileSync(target),mime[path.extname(target)]||'application/octet-stream')}).listen(process.env.PORT||3000,()=>console.log('MovieZone running at http://localhost:'+(process.env.PORT||3000)));
